name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag swissneifen/secret-h:latest
    - name: Push the image to docker hub
      run: |
        docker login -u swissneifen -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push swissneifen/secret-h:latest
